version: '3'

services:
  judge-sqlserver-database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - "1433:1433"
#    volumes:
#      - ./dbdata:/var/lib/mysql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Sy_123456
