version: '3'

services:
  mariadb:
    image: sqlserver
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      SQLSERVER_ROOT_PASSWORD: sy123456
      SQLSERVER_USER: test
      SQLSERVER_PASSWORD: sy123456
      SQLSERVER_INITDB_SKIP_TZINFO: 1
